# Generated by Django 4.2.6 on 2023-10-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('GSTIN', models.CharField(max_length=255, null=True)),
                ('UIN', models.CharField(max_length=255, null=True)),
                ('stateName1', models.CharField(max_length=255)),
                ('Email1', models.CharField(max_length=255, null=True)),
                ('Dated1', models.DateField()),
                ('Buyer', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255, null=True)),
                ('Email2', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('GSTIN2', models.CharField(max_length=255, null=True)),
                ('stateName2', models.CharField(max_length=255, null=True)),
                ('ModeORtermsOfPayment', models.CharField(max_length=255)),
                ('OtherReference', models.CharField(max_length=255)),
                ('descriptionOfGoods', models.CharField(max_length=255, null=True)),
                ('HSN', models.CharField(max_length=255, null=True)),
                ('SAC', models.CharField(max_length=255, null=True)),
                ('Rate', models.CharField(max_length=255, null=True)),
                ('per', models.CharField(max_length=255, null=True)),
                ('disc', models.CharField(max_length=255, null=True)),
                ('amount1', models.CharField(max_length=255, null=True)),
                ('CentralTax', models.FloatField(null=True)),
                ('StateTax', models.FloatField(null=True)),
                ('total_tax', models.FloatField(null=True)),
                ('tax_words', models.CharField(max_length=255, null=True)),
                ('Total', models.FloatField(null=True)),
                ('words', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
