# Generated by Django 4.2.6 on 2023-10-12 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bill_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('GSTIN', models.CharField(max_length=255)),
                ('UIN', models.IntegerField()),
                ('Buyer', models.CharField(max_length=255)),
                ('stateName', models.CharField(max_length=255)),
                ('InvoiceNo', models.IntegerField()),
                ('Dated1', models.DateField()),
                ('deliveryNote', models.CharField(max_length=255)),
                ('ModeORtermsOfPayment', models.CharField(max_length=255)),
                ('SuppliersRef', models.CharField(max_length=255)),
                ('OtherReference', models.CharField(max_length=255)),
                ('BuyersOrderNumber', models.CharField(max_length=255)),
                ('Dated2', models.DateField()),
                ('DespatchDocumentNumber', models.CharField(max_length=255)),
                ('DespatchedThrough', models.CharField(max_length=255)),
                ('TermsOfDelivery', models.CharField(max_length=255)),
                ('Total', models.IntegerField()),
                ('Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='bill_model3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slNo', models.IntegerField()),
                ('descriptionOfGoods', models.CharField(max_length=255)),
                ('HSNorNAC', models.CharField(max_length=255)),
                ('Quantity', models.CharField(max_length=255)),
                ('Rate', models.CharField(max_length=255)),
                ('per', models.CharField(max_length=255)),
                ('disc', models.CharField(max_length=255)),
                ('Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='bill_model2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bill_model')),
                ('bill_list', models.ManyToManyField(to='app.bill_model3')),
            ],
        ),
    ]
