# Generated by Django 4.2.6 on 2023-10-13 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill_model',
            name='DespatchDocumentNumber',
        ),
        migrations.RemoveField(
            model_name='bill_model',
            name='DespatchedThrough',
        ),
        migrations.RemoveField(
            model_name='bill_model',
            name='TermsOfDelivery',
        ),
        migrations.RemoveField(
            model_name='bill_model3',
            name='Quantity',
        ),
    ]
