# Generated by Django 4.2.6 on 2023-10-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_bill_model_despatchdocumentnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_model',
            name='HSNorNAC',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill_model',
            name='Rate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill_model',
            name='descriptionOfGoods',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill_model',
            name='disc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bill_model',
            name='per',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='bill_model2',
        ),
        migrations.DeleteModel(
            name='bill_model3',
        ),
    ]
