# Generated by Django 4.2.6 on 2023-10-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bill_model_hsnornac_bill_model_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill_model',
            name='Amount',
        ),
        migrations.AlterField(
            model_name='bill_model',
            name='GSTIN',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill_model',
            name='UIN',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
