# Generated by Django 4.2.6 on 2023-10-13 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_bill_model_amount_alter_bill_model_gstin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill_model',
            old_name='stateName',
            new_name='stateName1',
        ),
        migrations.AddField(
            model_name='bill_model',
            name='stateName2',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
