# Generated by Django 4.2.6 on 2023-10-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_statename_bill_model_statename1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_model',
            name='Email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
