# Generated by Django 4.2.6 on 2023-10-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bill_model_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill_model',
            old_name='Email',
            new_name='Email1',
        ),
        migrations.RenameField(
            model_name='bill_model',
            old_name='HSNorNAC',
            new_name='HSNorSAC',
        ),
        migrations.RemoveField(
            model_name='bill_model',
            name='BuyersOrderNumber',
        ),
        migrations.RemoveField(
            model_name='bill_model',
            name='SuppliersRef',
        ),
        migrations.RemoveField(
            model_name='bill_model',
            name='deliveryNote',
        ),
        migrations.AddField(
            model_name='bill_model',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
