# Generated by Django 4.2.6 on 2023-10-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_hsnorsac_bill_model_email2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill_model',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='bill_model',
            name='amount1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bill_model',
            name='Dated1',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bill_model',
            name='Dated2',
            field=models.DateTimeField(),
        ),
    ]
