# Generated by Django 4.2.6 on 2023-10-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_bill_model_options_bill_model_amount1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_model',
            name='words',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
