# Generated by Django 4.2.6 on 2023-10-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_bill_model_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_model',
            name='total_tax',
            field=models.FloatField(null=True),
        ),
    ]
