# Generated by Django 4.2.6 on 2023-10-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_bill_model_tax_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill_model',
            name='Dated1',
            field=models.DateField(),
        ),
    ]
