# Generated by Django 4.2.6 on 2023-10-15 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_bill_model_dated1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill_model',
            name='Dated2',
        ),
    ]
