# Generated by Django 4.2.6 on 2023-10-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_bill_model_dated2'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill_model',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
